# Generated by Django 5.2.7 on 2025-10-19 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('s_id_user', models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, unique=True), max_length=100, primary_key=True, serialize=False)),
                ('s_first_name', models.CharField(max_length=50)),
                ('s_last_name', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=100, unique=True)),
                ('s_password', models.CharField(max_length=100)),
                ('s_status', models.CharField(default='1', max_length=20)),
                ('d_created_on', models.DateTimeField(auto_now_add=True)),
                ('s_created_by', models.CharField(default=models.EmailField(max_length=100, unique=True), max_length=50)),
                ('d_updated_on', models.DateTimeField()),
                ('s_updated_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tm_user',
            },
        ),
    ]
