# Generated by Django 5.2.7 on 2025-10-19 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmuser',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='s_id_user',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
