# Generated by Django 5.2.7 on 2025-10-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_tmuser_uuid_alter_tmuser_s_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='d_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
