# Generated by Django 5.2.7 on 2025-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_tmuser_d_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='s_password',
            field=models.CharField(max_length=255),
        ),
    ]
