# Generated by Django 5.2.7 on 2025-10-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('s_id_slider_banner', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_nama_gambar', models.ImageField(upload_to='slider_banners/')),
                ('s_created_on', models.DateField()),
                ('s_created_by', models.CharField(max_length=50, null=True)),
                ('d_updated_on', models.DateField(null=True)),
                ('s_updated_by', models.CharField(max_length=50, null=True)),
                ('n_istatus', models.CharField(choices=[('0', 'Non Aktif'), ('1', 'Aktif')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Slider Banner',
                'verbose_name_plural': 'Slider Banners',
                'db_table': 'tm_slider_banner',
            },
        ),
    ]
