# Generated by Django 5.2.7 on 2025-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='d_updated_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='s_updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
