# Generated by Django 5.2.7 on 2025-10-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_sliderbanner_d_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderbanner',
            name='s_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
