# Generated by Django 5.2.7 on 2025-10-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sliderbanner_s_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel1',
            fields=[
                ('s_id_article', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_description', models.TextField(blank=True, max_length=200, null=True)),
                ('s_created_on', models.DateField()),
                ('s_created_by', models.CharField(max_length=50, null=True)),
                ('d_updated_on', models.DateField(blank=True, null=True)),
                ('s_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('n_istatus', models.CharField(choices=[('0', 'Non Aktif'), ('1', 'Aktif')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'Article 1',
                'verbose_name_plural': 'Article 1',
                'db_table': 'tm_article1',
            },
        ),
    ]
