# Generated by Django 5.2.7 on 2025-10-16 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_artikel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel1',
            name='s_title',
            field=models.TextField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='artikel1',
            name='s_created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artikel1',
            name='s_description',
            field=models.TextField(default='Untitled', max_length=200),
        ),
    ]
