# Generated by Django 5.2.7 on 2025-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_artikel1_s_title_alter_artikel1_s_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel1',
            name='s_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artikel1',
            name='s_title',
            field=models.TextField(default='', max_length=200),
        ),
    ]
