# Generated by Django 5.2.7 on 2025-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_artikel1_s_description_alter_artikel1_s_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel1',
            name='s_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
