# Generated by Django 5.2.7 on 2025-10-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_artikel1_s_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel1',
            old_name='s_created_on',
            new_name='d_created_on',
        ),
    ]
