# Generated by Django 5.2.7 on 2025-10-16 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('s_id_about', models.BigAutoField(primary_key=True, serialize=False)),
                ('s_title', models.CharField(default='', max_length=200)),
                ('s_description', models.TextField(default='', max_length=200)),
                ('d_created_on', models.DateField(default=django.utils.timezone.now)),
                ('s_created_by', models.CharField(max_length=50, null=True)),
                ('d_updated_on', models.DateField(blank=True, null=True)),
                ('s_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('n_istatus', models.CharField(choices=[('0', 'Non Aktif'), ('1', 'Aktif')], default='1', max_length=1)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'tm_about',
            },
        ),
    ]
